name: Helmfile Diff

on:
  pull_request:

jobs:
  helmfile-diff:
    uses: mocbotau/infra-workflows/.github/workflows/generic-helmfile-diff.yaml@v0.5.1
    secrets: inherit
    with:
      run-staging: true

permissions:
  contents: read
  pull-requests: write
